server {

    server_name sercora.serco.pro;

    root /var/www/sercora;

    index index.html;

    location ~ \.mjs$ {

        types {
            application/javascript mjs;
        }

        try_files $uri =404;

    }

    location / {

        try_files $uri $uri/ /index.html;

    }

}
